# Generated by Django 5.1.7 on 2025-04-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_profile_role'),
    ]

    operations = [
    ]
