# Generated by Django 5.1.7 on 2025-05-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_create_missing_profiles'),
    ]

    operations = [
    ]
