# Generated by Django 5.1.7 on 2025-05-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_create_missing_profiles'),
        ('tickets', '0006_fix_missing_profiles'),
    ]

    operations = [
    ]
