# Generated by Django 5.1.7 on 2025-05-10 16:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # Your last actual migration
        ('tickets', '0007_merge_20250510_2239'),  
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='unique_code',
            field=models.CharField(max_length=17, null=True, blank=True),
        ),
    ]