# Generated by Django 5.1.7 on 2025-05-10 16:55

from django.db import migrations

# tickets/migrations/0009_generate_unique_codes.py
from django.db import migrations
import random
import string

# tickets/migrations/0009_populate_unique_codes.py
from django.db import migrations
import random
import string

def generate_unique_code(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    for ticket in Ticket.objects.all():
        while True:
            code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=17))
            if not Ticket.objects.filter(unique_code=code).exists():
                ticket.unique_code = code
                ticket.save()
                break

class Migration(migrations.Migration):
    dependencies = [
        ('tickets', '0008_remove_ticket_is_used_ticket_unique_code_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_unique_code),
    ]