# Generated by Django 5.1.7 on 2025-05-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_add_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unique_code',
            field=models.CharField(db_index=True, default='D65CC0192D8549FD9', max_length=17, unique=True),
        ),
    ]
