# Generated by Django 5.1.7 on 2025-05-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticket_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unique_code',
            field=models.CharField(db_index=True, default='3A2DF7BC4C2D45A9A', max_length=17, unique=True),
        ),
    ]
