# Generated by Django 5.1.7 on 2025-05-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_ticket_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unique_code',
            field=models.CharField(db_index=True, default='F73F9D52BD4942238', max_length=17, unique=True),
        ),
    ]
