# Generated by Django 5.1.7 on 2025-05-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_ticket_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unique_code',
            field=models.CharField(db_index=True, editable=False, max_length=17, unique=True),
        ),
    ]
