# Generated by Django 4.2.21 on 2025-05-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('am', 'Amharic'), ('kri', 'Krio')], default='en', help_text='Language used in this message', max_length=10),
        ),
    ]
